Repository ponylang/ponylang-mode, pull requests merged in 2020-06, with the labels that each got.

#85 Added tuple references highlighting
  ponylang-mode.el
Labels: changelog - added

#86 Fixed generic references highlighting
  ponylang-mode.el
Labels: changelog - fixed

#87 Replace trivial dependency on Oh My Emacs
  ponylang-mode.el
Labels: changelog - added

#88 Fixed Incorrect indentation
  ponylang-mode.el
Labels: changelog - fixed

#89 Fixed type references highlighting
  ponylang-mode.el
Labels: changelog - fixed

#90 Added source file doc highlighting
  ponylang-mode.el
Labels: changelog - added

#91 Added use keyword highlighting
  ponylang-mode.el
Labels: changelog - added

#92 Fixed numeric highlighting
  ponylang-mode.el
Labels: changelog - fixed

#93 Added character literals highlighting
  ponylang-mode.el
Labels: changelog - added

#94 Added imenu support
  ponylang-mode.el
Labels: changelog - added

#95 Fixed character literals highlighting
  ponylang-mode.el
Labels: changelog - fixed

#96 Changed imenu grouping
  ponylang-mode.el
Labels: changelog - changed

#97 Update project run menu behavior
  ponylang-mode.el
Labels: changelog - changed

#98 Added playground support
  ponylang-mode.el
Labels: changelog - added

#99 Improve type refrences highlighting
  ponylang-mode.el
Labels: changelog - fixed

#100 Fix region length
  ponylang-mode.el
Labels: changelog - fixed

#101 Update project build method
  ponylang-mode.el
Labels: changelog - changed

#102 Fixed Invalid indent expression
  ponylang-mode.el
Labels: changelog - fixed

#103 Added TODO highlighting
  ponylang-mode.el
Labels: changelog - added

#104 Added whitespace highlighting
  ponylang-mode.el
Labels: changelog - added

#105 Added pony file coding system
  ponylang-mode.el
Labels: changelog - added

#106 Added fill column indicator
  ponylang-mode.el
Labels: changelog - added

#107 Added rainbow brackets highlighting
  ponylang-mode.el
Labels: changelog - added

#108 Fixed methods nesting highlighting
  ponylang-mode.el
Labels: changelog - fixed

#110 Update README
  README.md
Labels: changelog - changed

#111 Fixed condition indentation
  ponylang-mode.el
Labels: changelog - fixed

#112 Added source folding support
  ponylang-mode.el
Labels: changelog - added

#113 Fixed generic default parameter highlighting
  ponylang-mode.el
Labels: changelog - fixed

#115 Added underscore in numeric literals highlighting
  ponylang-mode.el
Labels: changelog - added

#114 Improved delimiter highlighting
  ponylang-mode.el
Labels: changelog - changed

#119 Added community menu items
  ponylang-mode.el
Labels: changelog - added

#121 Fixed match indent to be consistent with Style Guide
  ponylang-mode.el
Labels: changelog - fixed

#122 Added code jump support based on ctags
  ponylang-mode.el
Labels: changelog - added

#123 Added tags autoload support
  ponylang-mode.el
Labels: changelog - added

#124 No prompt for ctags update
  ponylang-mode.el
Labels: changelog - changed

#126 Fixed match indent
  ponylang-mode.el
Labels: changelog - fixed

#129 Simplified regular expression for indentation
  ponylang-mode.el
Labels: changelog - changed

#130 Fixed type alias highlighting
  ponylang-mode.el
Labels: changelog - fixed

#131 Added ffi bare lambdas callback hightlighting
  ponylang-mode.el
Labels: changelog - added

#132 Added struct support for ctags
  ponylang-mode.el
Labels: changelog - added

#133 Better imenu parsing rules
  ponylang-mode.el
Labels: changelog - changed
